### ISSUE TITLE
How to update the picture of a unique item?

### ISSUE THREAD

**Issue by xxxx0107** [HighTechLowIQ/ModdingDiablo2Resurrected#3]
At present, many unique items have the same picture. I want each item to have a unique picture, such as a ring. I tried to modify it, but it didn’t work.

  { "bul_kathos_wedding_band": {
  "normal": "ring/ring",
  "uber": "ring/ring",
  "ultra": "ring/ring"
} },

to

  { "bul_kathos_wedding_band": {
  "normal": "ring/customring1",
  "uber": "ring/customring1",
  "ultra": "ring/customring1"
} },

**Comment by HighTechLowIQ** [comment]
Hey! 

I assume this is in relation to the "[New Unique and Set Sprites](https://www.youtube.com/watch?v=y-yDdxPFsJY)" video? If so, the the problem is likely that the Ring in misc.txt does not have a "uniqueinvfile" set. Just set that to invrin, and the new graphics should take effect. That's pinned as the top comment on the video, but is easily missed.

It's one of the areas where the new and old systems meld in a strange way. That column isn't used at all for the HD graphics, but it seems like if it's missing, then the unique HD graphics aren't loaded.

Let me know if that works!

**Comment by xxxx0107** [comment]
I tried it, but it didn’t work, maybe I got something wrong

**Comment by HighTechLowIQ** [comment]
Do double check everything - and maybe try with a different item type as well.

Rings do have multiple inventory graphics set in the itemtypes.txt, but I'm not sure if that would affect it. I haven't tried myself though.

**Comment by HighTechLowIQ** [comment]
![image](https://user-images.githubusercontent.com/84676641/140061556-b5b2a27e-5db7-43c4-91f5-9c684874183d.png)

Just tried it myself, and I could change the image of Bul Kathos' Wedding Band.

Below are the files:

[misc.txt](https://github.com/HighTechLowIQ/ModdingDiablo2Resurrected/files/7467534/misc.txt) - just changed the uniqueeinvfile column.
[uniqueitems.txt](https://github.com/HighTechLowIQ/ModdingDiablo2Resurrected/files/7467538/uniqueitems.txt) - just changed the lvl and lvl_req columns.

(Can't attach JSONs)

\data\hd\items\misc\ring\newring.json - copied from ring.json - only change was UnitDefinition name to "newring".
\data\hd\items\uniques.json - changed normal/uber/ultra on bul_kathos_wedding_band to "ring/newring".
\data\hd\global\ui\items\misc\ring\newring.lowend.sprite - updated the graphics here
\data\hd\global\ui\items\misc\ring\newring.sprite - updated the graphics here

Hope this helps.

**Comment by xxxx0107** [comment]
Thank you very much, it helped me a lot!
